### ISSUE TITLE
Can't add product-id to getProductTicker()

### ISSUE THREAD

**Issue by michelem09** [coinbase/gdax-node#20]
How can I specify a different product-id? I mean something like this is not working now.

```
publicClient.getProductTicker('BTC-EUR', function(err, response, data) {
	console.log(err);
	console.log(data);
});
```

**Comment by loriopatrick** [comment]
In the public client constructor you can specify the product id

```
var publicClient = new Gdax.PublicClient('BTC-EUR');
publicClient.getProductTicker(/* callback */ );
```

**Comment by awitherow** [comment]
@loriopatrick so I have to initiate a new client for each coin I am looking for? Is this more effective than passing a value into `getProductTicker` in some way on the side of coinbase/gdax? It seems to lead to a lot of extra code on the user end.

**Comment by awitherow** [comment]
And what about the`authenticatedClient`?

**Comment by fb55** [comment]
Fixed in #52

**Comment by uniquarkD** [comment]
It's still not fixed on the master. We have to create a public client to get the ticker even though we're using the authenticated one.
